Vagrant.configure("2") do |config|
  # This lets us specify a name for the VM that will be used later in the
  # generated ansible inventory file, making everything easier.
  config.vm.define "dev-mongo-redis-vz" do |dev|
    dev.vm.box = "galahgroup/centos6-x86_64-vbox-vz"
    dev.vm.synced_folder "../../../", "/opt/galah"
  end

  # Provision the VM with our Ansible playbook.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/site.yml"
    ansible.sudo = true
    ansible.verbose = "vvvv"
  end
end
