Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 5000, host: 9191, host_ip: "127.0.0.1"

  config.vm.define "dev-server" do |dev|
    dev.vm.box = "galahgroup/centos6-x86_64-vbox-vz"
    dev.vm.synced_folder "../../", "/opt/galah"
  end

  config.vm.provision "shell" do |shell|
    shell.path = "install-mongo.sh"
  end

  config.vm.provision "shell" do |shell|
    shell.path = "install-galah.sh"
  end

  config.vm.provision "shell" do |shell|
    shell.inline = "yum -y install vim screen"
  end
end
